# https://spring.io/guides/gs/vault-config 참조
services:
  vault:
    container_name: "spring-cloud-vault"
    image: hashicorp/vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 19aefa97-cccc-bbbb-aaaa-225940e63d76
    ports:
      - "8200:8200"

# 실행: docker compose -f docker-compose-vault.yml up -d
# 1. docker exec -it spring-cloud-vault sh
