server:
  port: 11200

spring:
  application:
    name: api-app


--- # local
spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:anything-common.yml

--- # dev
spring:
  config:
    activate:
      on-profile: dev