version: '3.8'

networks:
  kafka_network:
    name: kafka_docker_net

services:
  kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-1
    hostname: kafka-1
    restart: on-failure
    networks:
      - kafka_network
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      # 기본 설정
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      # KRaft 설정
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_KRAFT_CLUSTER_ID: "tsQVPtWPRKKd5YNZeZ_j2g"  # 모든 노드에서 동일해야 함
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"  # 컨트롤러와 브로커 역할 모두 수행
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:19092,2@kafka-2:19093,3@kafka-3:19094"
      # 리스너 설정
      KAFKA_CFG_LISTENERS: "INTERNAL://:19092,EXTERNAL://:9092,CONTROLLER://:29092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka-1:19092,EXTERNAL://127.0.0.1:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      # 클러스터링 설정
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_CFG_NUM_PARTITIONS: 3
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 6000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      CONFLUENT_METRICS_ENABLE: 'false'
    volumes:
      - ./kafka-1/data:/var/lib/kafka/data

  kafka-2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-2
    hostname: kafka-2
    restart: on-failure
    networks:
      - kafka_network
    ports:
      - "9093:9093"
      - "29093:29093"
    environment:
      # 기본 설정
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      # KRaft 설정
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_BROKER_ID: 2
      KAFKA_KRAFT_CLUSTER_ID: "tsQVPtWPRKKd5YNZeZ_j2g"  # 모든 노드에서 동일해야 함
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:19092,2@kafka-2:19093,3@kafka-3:19094"
      # 리스너 설정
      KAFKA_CFG_LISTENERS: "INTERNAL://:19093,EXTERNAL://:9093,CONTROLLER://:29093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka-2:19093,EXTERNAL://127.0.0.1:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      # 클러스터링 설정
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_CFG_NUM_PARTITIONS: 3
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 6000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      CONFLUENT_METRICS_ENABLE: 'false'
    volumes:
      - ./kafka-2/data:/var/lib/kafka/data

  kafka-3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-3
    hostname: kafka-3
    restart: on-failure
    networks:
      - kafka_network
    ports:
      - "9094:9094"
      - "29094:29094"
    environment:
      # 기본 설정
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      # KRaft 설정
      KAFKA_CFG_NODE_ID: 3
      KAFKA_CFG_BROKER_ID: 3
      KAFKA_KRAFT_CLUSTER_ID: "tsQVPtWPRKKd5YNZeZ_j2g"  # 모든 노드에서 동일해야 함
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:19092,2@kafka-2:19093,3@kafka-3:19094"
      # 리스너 설정
      KAFKA_CFG_LISTENERS: "INTERNAL://:19094,EXTERNAL://:9094,CONTROLLER://:29094"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka-3:19094,EXTERNAL://127.0.0.1:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      # 클러스터링 설정
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_CFG_NUM_PARTITIONS: 3
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 6000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      CONFLUENT_METRICS_ENABLE: 'false'
    volumes:
      - ./kafka-3/data:/var/lib/kafka/data