server:
  port: 11000

spring:
  application:
    name: core-app


--- # local
spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:anything-common.yml
      - classpath:kafka/kafka.yml
      - classpath:telegram/telegram.yml
      - classpath:vault/vault.yml

--- # dev
spring:
  config:
    activate:
      on-profile: dev